### ISSUE TITLE
Error when using the SDK methods with a local image having "webp" extension.

### ISSUE THREAD

**Issue by adilentiq** [Runware/sdk-python#15]
### Description
Currently, imageCaption() is not working with a local `.webp` image, I'm getting the error below.
I think the issue could be in the Runware SDK, `venv\Lib\site-packages\runware\utils.py`, the fileToBase64() util function returns:

```
data:None;base64,UklGRnZMBgBXRUJQVlA4TGpMBgAv/8G/AI1ADNg2bGPScdlM4P8HJ90NEf2fAF71TyQJPRGwQTlJco54ePQbrg0niarMXkuei38UQHkTa0lGVxIlUvLyEwbUom+l9Mf8w+w+gySNJAH61zmPevQO6H/wpn/4+w8zDyi8gfy1BJKGHlQekoTAUlJYSxrntHVbW2tJICnstbYkWU6BAtLn0rqS7L3X3ieq7RZ6cCVd11rXN+y9t9M+EuhtV7TXWusK2/d9Roq/Ttpij9R+vdb6ssGMlr1ewLak/uEH+LCWPB49x4xWjPEC2+dYkuayNNq+JMkHvBbYp5GmTSQJAzNjw5vtb89JEuQZu7XPAd6+SbW1TyzzkZiPfRgWtrlyRpoZ2x6Jwbdj4CXfA8ObLWZ8e34w38tA+8MHfFs22J7humhn3s5j32hs1iPfuDknseW/eOa+KY9lpt8vbZJ0hKzhvl08P/KlSSQeknzfCNsPkjiJJBCyxvdpf7WNGf0CmE77Q7yKNxIQQh6vtUbMjDQ8BZLQ034gSSOhn/BA8rhrHiCBhCSeQsC4e9OR5u0VGAnB5b23j6TOrwoG6QNc194zu1Ul5kUCJH0+dsK2t1oKkqhUoLTYvsCWWlGAVhKcCnB8MbGktA0U2kLbipMYv4inoC1UKkASjV4pAjQjaItGUiUluhB7qwFGw+dzfdijtJ9PklzsSm1AtPlc19znnLt5iSW1BTSnTbjvu3fbvnydFNqLc9LW933uviffr69A20JyCufu3c/nLbHFeaRJ8f0sTCSnti3byuBaNg3B/KM6TWsPcrlsDotlnYO307Z127ZtLSqyIimSImqqrn5s///Xzfe3tT54O21bt23b1oKurZdP6///rPET0nqvuqbJmqrKiizr/wSQ10hmMFBK0aYXYXE4RDx66/3FEtybFZt73CillOJUVbUlhPL2B5pouxRXuPpIebCJxXLjXm7FiThkKIMWRaxNeWdTHoMv7hFDvgKV6ovNawwvN74Z441mREqN1Jby2BgR8Y7L9eVbOilS57O+PMZm3/SiPJdvPnAN18bBLLmHZ7w09wmLxWaOJ7MbPZxncCJwRhTefvveLGDx4rW5ds1e2yxPl+XJBy7GySYSueLKiAwHsQEDlY7eGk+N4VvzgSzqdA8Li17UpjZZZJFFFpEozxoZhuE6oaBric38U46OtYv8X9ta7mEfzDAc0lhsu7TIPxmHM7KwqUUWWWTxZ/GH4R8y5xyW4a+Ff34c88+r/EAdZ9RfWjoyEgEyiywix/6Y2DHJoZNS5wDQTwGQcI7EiokVEz32ikVkpJWz5iuXACKPIGARmC8HjQ4Mzw55vnxt/mWnm8wii1qE7YyEgUbBYSmP+//5wcZCOWu+L/cThFeycpQAD2DsSKSE3j5BkAMiIuWx4Jd/CLwEBgWBNCk1JTYAJtGLkQEwm+BNiuXyWOTwDwHJI79ZNwx/1cNi7ZQg4T8AEl0JAABKSsKAL/iAexC54MBwSUuzhgawAZyVmyDgjDLYAOTlBbBQRoDfgCGEADQK1CcAPATZCAPEQgEdnMhfwIyZSo61ZLMRAZrR0r/CBiDI4uUgItkequLqkmwhyINrMyuUAqxS4gMA4BNAbhIFFmuzEJGydGkZyrS9SoiiEBYIQDw4OOe2WQqsEn6QIuIhkkf+RUSuLF0sQM64gCPzdOTGoovC4qOL0SIiRXYdYn/1cTZzUddPS3hgDIRQyr27Vh5oiWxFl7JASoH9LzuSM9X9bh9FPhRxDLNmGU2WWXtxuKQn/1f0bFGQ0FLalPOb0z1fVZFLcTjCrAvR6pYFLYxWYIi6XbQVi5ReCliql3uIiL/aTgFLS8daeeTurOoobMpgk4iUUiCH3OGkSPDWyAIhpVE4UGC5pIiIOCwCL6EUh6yFAwmKDwJj9e5i0fgCl4gkf+kokmKIhhu3tdd/B8MswgJwtyweNpvDIfIiIo5hGIqIPIb7pcdd8sFsIgEgrly42UObJfJQwNbjDjmUh4fKQJOHrp9FEAkACOsoCmTdx1DOIT467pBL+Wk/yLCWiMi3fCMB4NddUyy75LHXHnvttZtcPuMz5GEGgMza78tf91+HmGB8swjAIlKvPx8/n/Y/8r522+y12Ssro+Oz5CAiQtsf/fXEzZCbIEMAbqYzLT1K3uaWh+yRh0iHiDxrrfAhRx5lDo859vrGGwCMrmEYgnjEcJtHxwynqkg9NMnhXqxhGO5YyzCg/YVwvWso5UJx9mptDlt4EJG2khvbiwwvYbUVZpNNg3I0P385Lbc2x3nkJiLKaV1vueuueRHJyMp1JzfZ2NDtWdw4CnPR+Fg3xxmdPk3k8KyB1Rs31uUCGG5cqHf8AcS7dvB2H5d7XFinnHbmdW63rZXlYpW2Fh63HQ4SuOALAfydMWs+GCmXe1zAW76m3be0tUr3mtWWt666Lp/xGR7ghSCAIvMhBkHhqEsY/ThfHLl1iMtlyS/W4dAhLpEGARbLT/CD1svJ3LJubT26zm23U1oWTFI3hRak4zPOGByQ2qT8hJ+iIDTiJHnLyXRzyUrp/XaXXUo7LecpSxc4StawKUH3WV5ExMXyk3R3Z69nFZpfu+yyf93g25zhekjPQJ2yxOVyK2eIiIDtbvZtHRkdEHgeyn7eEhN8ZbihnXiOLJbLwiOCA1kwDIPNff/9ZRiMS6iy9vP2DQJguDBcBCVBWQ1B+DmwFDjkNg6CRqFeThcH5XXRXwiLhIcLcKNMoaRllTLCK7xAR4djDh4EZT0/1ggP8FFe4QWCrN75yhtlyrmdQuFW4WXK4VA6HLPmQfB9+AEyyGIdqwaAtVqCQskH/zN1cduPdVMgtJEkScqof6qbP+GZvaMQERMgVRVmbubmBZhblZUVgEpT7uZvpkrC3dzc3Quqhf+kMkNo/I+0xn9PViCx/IX+A50wmlEDzmvosh8jhrfazfxzwMzybV18T2P5Wa38bStmXjT5GQ38oYfpZbe77WXTVmuZNVXFR7O7TVWNsZk5U8+T6VWz/FRlZj5nLNO7siScqmFmlh5M0xkzZlNV4G5UDkOPBtxRVTL2ZEru7lQW7O7zhTLzsSofxyM8X8w8osyBzswnE+GZ+TWzLVVVOJqZJx0gLamGYfqquzLDNZlVTjl1u6Xue2+3WuouUFUVOHtWEkitxpH63stUFeC9Z/npYO7MSyihXHNO790rB87Z2bP3ilJlml9Wvbt3X33POcu2qOpKm0PP3HPPepmZ1QzSvVBTaXtmevfe246ZubnTurcDMn13ntFuD68yc7r73o2YDD+HoYW7/zAEe24kmV8Cd3MwzBIxe06EZ9Z54MN+uKPp1s2MTAcEyM2K4QtJyneBNCDAEW+13vXKc3bPMgIQArHn9N6POufZc/T5ej/nPHsqs6pOwzzw8Ja0rRlgKiLTG0oqfwaQpCMkSlRkegyA4h8NOBMZkdCtLv4UjQaKikx6WvOXPgoktSo9MwRIfLck4YDUkZnh7gEjGGAkAZJEeWS6B+EIDZ8fIMndI90Ld4fp+WgACZWbu0RVZHDOOUMV1LYELUng7tXFOVcaiojnnLPSNtAD7h7nzAADFdDnLDjs7WmAigigJ8IB7XGc3XObFpDu7G4/wWcBvQy9I4kKZoDefQWgp3d6AElkgUQPj4iYz27f2jYpkiTb1v+LiKqBe0QkFTX3oDlo4lprMzMeMuMZw6XsC2BmZmaazHMO6O7RUJCZAe5uZqoqIgcDn7FvwLckSZYkSbZFxKKRNeecrzr/tS/ds7/r3H7pulZnmAh7r61t2rY9Ttba9vN+PlUKjoTeUjkKggGXDETV95ANP136nvvYtpgAz7Jtq7ZtSVJtrY+59j73vvdUjZwpmJnSER+CuZBIcSo+BrPMHJFjZmYwM3dTU9X37j1nrzl7awlVc5D4AW+2bTvbtr3JGHMd1/t9Iuf8i3oki2IFf+/zGSgWlqA0OYOt9772nL4jyXZt27adiKx97nMfiAQwqMLFYvee80DEoopwTj6Bd8+erURMgG9JkixJkmwLSSy71nXf7/v/f3KtrlB+yJwLwPoBD4IkKbJt25ao59r7MuNjbOjt9MM9K4xCGEmSBEdRc0DN5MPt7YwJ8CRItmxJkiQBnifm+19qDiNC5V8amEWbG/Ak2LZsSZLk0DpPPDEsIB3jQphKYGDInBZc/90eY9sWbUmyldbnvlFmaAWawFOksp4hCKK8rwl6/DhrxAR4kmxbtiRJknDdT1ZNwuY/OC+bAkr/7sanTyJEbAPwLUiSJUmSZAGyRvz/z/a9w4R8S5JkSZJkW0hiUbNg/f/XrjXpyjEBnmxtmyRJkqP7sFr2fd8Oc5rTDphiD1hFtwJsAtvA1nrMMsL4HRARMwmpL8BiJEmCbEUete+DXJxix0Pu9zp9C5JkSZIkWYCsmVn3///YShOKCfBs27ZqSbIg9bnPvSKqBm7mbo9fMDMzc8QnRCSVskU5Ocv8BVlmLGeVmZnzMYO7mxuomqqI3LvXLCiJqvoH+JYkSbVt27bUI2trfdDcc9FmZsanffi/8Q+YmWnR4DF6763VDPcc2bZq27ZteSptzHXOfxD6DAJ8LVh/LX6M8d639xw1xwT43v9JkSRJ1nf2ExFVNTPnwOQs7moaXuY9zMzM9DK/98x0dZiZmc8Z7t7pbSxqKMiqrMTIyAAnM1NVEbmYeabn1HiQJMmRZNu2RNU8snqtve9778OZYPwHdsC+l96kPrhwKh/jA/Ze3RVuqn5j23Zt27adnEttfay9L5G+/Bz5H+y+9+LDKfx3yPUKnANeIKBzdu/ec/RWS0yAb9m2VduWJKm23seYc62997mgqobhGByRzJz5xE/0k8zMzODMpmqoaqqXD+y91ppz9N6S4eoPeLJt27Vtu5Fa62Puc9/7HyBda609Ax7TnisTePc+kpYqlywe9ahpLakJ4It379lrjs6xtm1XeyNJa+1z3wdERFXrNqAN0dIoRYCRjrQhutsbLTNI/O+eHROASbZt1XYkzbXPufe+D/6/WApmZqpliRqQlr3INmULOOuZJWZm8mCOkL4+vnfv2XsV5FGRqwG4Zdt23UbSXHufewEQdFLa8D6z2vsn3/1fFUVmV/1cf0A/ed+dIUUqRQPce8/Zy5ckSY5k27YlquYRWVUTbIx7CkflWGN3EPVg7184UGWGm2lMAMf/v01bjvVv6zvGmHNp66CcqpSSdCet9LX12PjZtm3btm0b1/c+V+004krKdU4dbSzMOccYvAZAUiTb0WRm7hGZ1X3gSpqrb5mZ6WnfmXn/BfNKMyNY/EvMDG/MODyae3Xv6a7MCHfjbdu2a9ttpNb7mHPtfe4FCJKK9N77zHefYf8onxSFAMNHfFJ6bz7EpxwA4t5z9ppj9AiP2/8pkuPa9sY+AYnF1axWg1gaScPj8ZjtNV5mezMzMzMz817MzAxmHmaQRtzdaubq6qrKqqSI2Hufw9u2bVO7bVu5oNba8H3fr67hiWXsY9u2/QDncntM9aGlo1c4l+c8wLkyt+1pjN776Pr1oaGiFN7aNimSJNn6fxFRVTN3D49IqmpaM5uZmZmZ8UawZxV09+J1vK9hHzEzMzM0c0FmoLuZqopITIDHbdtVqe3/f2XPku17XBgGJxAnXknqfXnl5f56u7u7u7u7u1vt1bxfaeNp2iTESwhBBxiG8e1rrce3bUuSJEmSdC8AIBIxi4iNPvtb/EZ8db7myo/If/ApRjNTVWFmIkIAuL4FQHIkSZIkImIWUTWzcI8Eg/ET+owG89t4/gBjjEGhiHA3UxFmivjP8v9/9btzv/s6ZVULsaEUIg3VijQQFGGUkCxHdXbsdl5jhyUwmhj2pt09eHfz7tdDu7e7uLf72cPegz1wqUtdY/cuPPCQXp5v6z73crtLm920QQJrDlkCqagpomita1o2AA0j6NkgBIRAgFVECgBQbAC2giWwiAEYgQW/W/i3MwAgAGAAQAz/WsK/LIQAAAEAwn+MFYDEsAIS2AoIWmqE/7nWxIgVQGN4ZwgEAAgAIQAAIeDvDUIAAAIABAAAAAIEMPyLDAQADAAxAsAI/3oGAhgxAIRXmZSGREk0oEkBAMRSFQplGKFxTAzoAkURY6DAUp1SIRxlr1w5pTLdqbjqLrGuEyIkiaXGSkAkogQ1NXUWosG3dkQDz8i8Y4HJKAlIn3u/Hb9zv8l9xm940VUmO/Xsxh3eocFhhxs63KEJhwwHhg6NnDlw4OCrnu0Fr+2jO91B553qKefNiCa4AJmFwScwZjij6+Ks1Re9dd6+xz94TP/Bv3+Z+rtPWOmcoEsVALA4SSADHRp9PA7/4OvOMBho7rQ/CsKOzTMEG+Ea2UuaVFr1aQkH2utUa69a4JzHOyGfTIMAQFpUaO3GRcuBtW1WjFKTGAKaBUbVoyIwVrU6hayqFv64aoBVA6waYAU0qwbAqlkBaFbNf1o1IIbfSSwIzB9WABIACAACQgBgBACQ/JuF32vAKlYIrBAEQGAJAkATQMmrAKYBFVINEBNEAAACISZQ1SgAAAhAdQKNCggx6kRVJiADGagAKArQCgNUgKqatdVArJi14I9BAARAYqu0YrDkXwVYAPHQFEq6ppjWXIxUSWjJJoWmSISG1hQkFlcJjJgFBuwJYJWUfkgGgKUmx2rc6kAxQVAhBCxxnREkIkpKNEVJDIn4gM7E5MPKLhBqM5wtPhMiSGAUkWu86Kd5xZ/w6EWDZzt4cWcbd+ACczCJwBMBhyAgbloF0VqpqVSClVMlx1PfZKah4sjpC5Lhotc0yViCAQQTlWdQjn2+OOvVFJAsq9TwQGXrcwAUj0nzM7s0ebY6JD709495Ves48WCv5trtiUM2Wo9+tctcKi5MrFbZVzJS6WWcxpqSEkkSNLyxsdyiIXZRljHpKH0TDQYAtQLACqpWinCaGIBACNBghT83q2YVA//+2QQA0iP4MwHSAAAxKCMIrAIQUDYQAwWgf0OsAEaMAgtiBcQqVkH4d8GrGoBSJVSTJsWqAKBZAZgVgFn1iAJMQFBhAJrVAqCBQIIimwAsQKCsCACGKgRIgAogtNNQwxRlWQVhIFZArNgqsVUQVsGIgTAE1m9LSyqBlFQ0ISuGrGiIVUtNqBGCBIYmhQhCbEIBJhZYQZBeJdOQEqjSNVGqkSKsACBWqBGwCpJpEliEuBIJgBI1TamZJnumagMIaAuygRAqOHDI7tUb35DROPOQ3WxHXhNAmNoErjIvqdFLotEo8YhiEdYDCQV7Mo8Bw6UAepC9RCnipKYSgHIjpJGTQkf/5vvsVfQ4Zcmaan3JJSZNzVvW2IA56yzy5cWyCU+dJG63+kT6ZgyCEyikbF1Oqy+5Mlrd5Fvr6Gc6YVpbkgRdaAKBvUbQina1OsJ0lTpsUnJgeD0IVSEIqAD/dMUCIPg3CloAAsjQkpZqIlQWiMhaoppAREaRBRVJgBCjcDxOQ4IQ/HtWAAmsAGYxABQyAEwMbAULIMSqxCpIQSoatG4dBeN4KPEBWgACMANFJJvHEzVLIMDMqgKzi2YyZ4jzs2dsGlJcZ5LFCSAmOoYJcZCwSpnEKpXjVSGwVWCSwCvArMBgASuzAnsy7A2GtViPWDGtaqgwk2pDU6mTN0pvFCHBKmhNSAagQSFmMBAjQWCCpBErQChgAYBGIVgBMaGCDetiJYvTOhBpTVHUYAQIzW5MFJQWtKEAUIQDQG0AMlOqYTcDBATulICBYYcC0QrAQATwTB4ybcTXQ6AwJIgweoS6skU6KgKvC2YKhNRv+X0yS1TMKDURQmAXo31Uhs/C0PX+ZAgj/cte5HAvK1r34HPX/YJBamrNack4xn3dfn/27wdoYo2CsyMGmzjudWy3OHTMxXLI2QeaOQ1Ac8QYXq+BCkpNRjXomjRG7HUQAAEACAAA+BcagMBiaaFRqi1uUnZIK1qde0q0rkVEaqKcRYl03lndedxNqd1TokQWobKIpiokIQAcNKiAC1Se5OaFhIqq4N8ZYwiCWEirMWDxhLcOhAlREaLEIpVgHcXqNKmU9vY0rbO1mWh6QK7wmJlPZAgLT2hxaVhh7/U2+O7uXzxHB8mldHRPtRAEUEFkUXA1hSacUYIyvSzOElUbKA4PHJYMOh7mwLMWmAVjZbFpmdbN227MxjAPjOYKv/qkkr6dJ9V0uuHqNve5a9sJqpJCQxNaaJIUlZUpKwQGIzAQI2IgBgApoVEjBWU0AsMqjBhltKY4jTURklV4lRgMZCLMIgwFAQAC4cAqBIAA4CmsAJogAAlQb6HOSHC1EMBTjXgPez2q1utlUbgWx/wGEZ5YWskAHi1Br6cIjRot4ogCFKhUWRmdCNSuMGNDUQHosBczODlH5ih9B/EBhTrhTC2Mst29cB2SFDAl4tjFVbrUTqtW7nCRzJ5iAAEMACMCe51pMW1UkwEMaAIDw9sKBUJEUwuVNtVtUW7FWajsptzu2mc3v+zjs0N3+Szim+Mszs5SRBZVRBade52lzj3R7V7dosRZnq6VF5GpUJEJIEAIQpWARAZBJlXcRRKAh7F6OLBCSQPrxgAPzLln9Q56t+6koGUsrSy
```

Current error:

```html
runware.utils.RunwareAPIError: RunwareAPIError: {'code': 'invalidImage', 'message': 'Invalid value for image parameter. Image must be a valid string representing the image in one of the following formats: a data URI string, a base64 encoded image, or a publicly accessible URL. Supported formats are: PNG, JPG, and WEBP.', 'parameter': 'image', 'type': 'string', 'documentation': 'https://docs.runware.ai/en/getting-started/image-upload#image', 'taskUUID': '15f26921-0f45-4599-9811-691cd0f15005'}
```

### Context
Runware Python SDK version: `runware==0.2.7`

### Requirements
 - Python installed on your workstation

### Reproduction steps

1. Create a directory

2. Create a file e.g `my_test.py` with the following content:
```python

from runware import Runware, IImageCaption
import asyncio
import os
from dotenv import load_dotenv

load_dotenv()


async def main() -> None:
    runware = Runware(
        api_key=os.getenv("RUNWARE_API_KEY"), url=os.getenv("RUNWARE_WSS_URL")
    )

    await runware.connect()

    image = 'image.webp'
    payload = IImageCaption(inputImage=image)

    print(f"Payload: {payload}")

    result_image = await runware.imageCaption(payload)

    print(f"Response : {result_image}")


asyncio.run(main())

```

3. Create a virtual environment
  ```bash
  python -m venv venv
  ```

4. Activate venv environment
  ```bash
  # Windows
  venv\Scripts\activate

  # Linux/MacOS
   source venv/bin/activate
  ```

5. Create a requirements.txt file with the following content:
```
aiofiles==23.2.1
asyncio==3.4.3
python-dotenv==1.0.1
runware==0.2.7
websockets==12.0
```

6. Install project dependencies:

```bash
 pip install -r requirements.txt
 ```
 
 7. Create `.env` file and set up environment variables
   ```bash
   touch .env
   source .env
  ```
   
   Example
   ```
   RUNWARE_API_KEY="your_runware_api_key"
  RUNWARE_WSS_URL="wss://ws-api.runware.ai/v1"
  RUNWARE_MODEL="runware:100@1"
  ```
  
  8. Add a webp image in the working directory e.g `image.webp`.
  Note: Github doesn't allow me to attach here a webp image.
  
  9. Run the python script
  ```bash
  python my_test.py
  ```

### Actual result

```bash
$ python my_test.py 
Payload: IImageCaption(inputImage='image.webp', includeCost=False)
Traceback (most recent call last):
  File "C:\Users\andre\playground\image_caption.py", line 26, in <module>
    asyncio.run(main())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\image_caption.py", line 21, in main
    result_image = await runware.imageCaption(payload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 346, in imageCaption
    raise e
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 342, in imageCaption
    return await asyncRetry(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 43, in asyncRetry
    return await apiCall()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 353, in _requestImageToText
    image_uploaded = await self.uploadImage(inputImage)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 663, in uploadImage
    raise e
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 661, in uploadImage
    return await asyncRetry(lambda: self._uploadImage(file))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 43, in asyncRetry
    return await apiCall()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 728, in _uploadImage
    raise RunwareAPIError(response)
runware.utils.RunwareAPIError: RunwareAPIError: {'code': 'invalidImage', 'message': 'Invalid value for image parameter. Image must be a valid string representing the image in one of the following formats: a data URI string, a base64 encoded image, or a publicly accessible URL. Supported formats are: PNG, JPG, and WEBP.', 'parameter': 'image', 'type': 'string', 'documentation': 'https://docs.runware.ai/en/getting-started/image-upload#image', 'taskUUID': '3097c2ad-5917-4185-9e9c-fbc8d611dd1c'}
```

### Expected result
As a user I want to be able to call imageUpscale() with inputImage parameter: an URL pointing to an image.

**Comment by adilentiq** [comment]
Seems to be a general issue, it occurs also for `imageBackgroundRemoval()` method.

Python script:

```python
from runware import Runware, IImageBackgroundRemoval
import asyncio
import os
from dotenv import load_dotenv

load_dotenv()


async def main() -> None:
    runware = Runware(
        api_key=os.getenv("RUNWARE_API_KEY"), url=os.getenv("RUNWARE_WSS_URL")
    )

    await runware.connect()

    image_url = 'image.webp'
    payload = IImageBackgroundRemoval(inputImage=image_url)

    print(f"Payload: {payload}")

    result_image = await runware.imageBackgroundRemoval(payload)

    print(f"Response : {result_image}")


asyncio.run(main())
```

Stack-trace:
```
andre@mylaptop MINGW64 C:/Users/andre/AppData/Local/Programs/Microsoft VS Code
$ python image_background_removal_local_file.py 
Payload: IImageBackgroundRemoval(inputImage='image2.webp', includeCost=False, outputType=None, outputFormat=None, rgba=[], postProcessMask=False, returnOnlyMask=False, alphaMatting=False, alphaMattingForegroundThreshold=None, alphaMattingBackgroundThreshold=None, alphaMattingErodeSize=None)   
Traceback (most recent call last):
  File "C:\Users\andre\playground\image_background_removal_local_file.py", line 26, in <module>
    asyncio.run(main())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\image_background_removal_local_file.py", line 21, in main
    result_image = await runware.imageBackgroundRemoval(payload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 418, in imageBackgroundRemoval
    raise e
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 414, in imageBackgroundRemoval
    return await asyncRetry(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 43, in asyncRetry
    return await apiCall()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 425, in _removeImageBackground
    image_uploaded = await self.uploadImage(inputImage)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 663, in uploadImage
    raise e
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 661, in uploadImage
    return await asyncRetry(lambda: self._uploadImage(file))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 661, in uploadImage
    return await asyncRetry(lambda: self._uploadImage(file))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 43, in asyncRetry
    return await apiCall()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 726, in _uploadImage
    raise RunwareAPIError(response)
runware.utils.RunwareAPIError: RunwareAPIError: {'code': 'invalidImage', 'message': 'Invalid value for image parameter. Image must be a valid string representing the image in one of the following formats: a data URI string, a base64 encoded image, or a publicly accessible URL. Supported formatrunware.utils.RunwareAPIError: RunwareAPIError: {'code': 'invalidImage', 'message': 'Invalid value for image parameter. Image must be a valid string representing the image in one of the following formats: a data URI string, a base64 encoded image, or a publicly accessible URL. Supported formats are: PNG, JPG, and WEBP.', 'parameter': 'image', 'type': 'string', 'documentation': 'https://docs.runware.ai/en/getting-started/image-upload#image', 'taskUUID': '79538b9f-3c57-42a8-881b-ab8082856cab'}
(venv)
```

**Comment by gorantosicpf** [comment]
@adilentiq Added support

**Comment by adilentiq** [comment]
I confirm, works fine now with webp files.

Examples:

```
Payload: IImageBackgroundRemoval(inputImage='image.webp', includeCost=False, outputType=None, outputFormat=None, rgba=[], postProcessMask=False, returnOnlyMask=False, alphaMatting=False, alphaMattingForegroundThreshold=None, alphaMattingBackgroundThreshold=None, alphaMattingErodeSize=None)

Response : [IImage(taskType='imageBackgroundRemoval', imageUUID='10ab8383-72db-4f22-b0cc-0533ad5d7652', taskUUID='cf4345e1-9ce6-485e-88c1-23e41185a2a0', inputImageUUID='92f4d363-1183-486e-b730-b8e50dd335c2', imageURL='https://im.picfinder.dev/image/ws/0.5/ii/10ab8383-72db-4f22-b0cc-0533ad5d7652.png', imageBase64Data=None, imageDataURI=None, NSFWContent=None, cost=None)]
```

```
Payload:
 IImageCaption(inputImage='image.webp', includeCost=False)

Response :
 IImageToText(taskType=<ETaskType.IMAGE_CAPTION: 'imageCaption'>, taskUUID='2d8feac1-8ed1-4311-abd4-e41427003646', text='close up of a woman sitting in a car with a helmet on, fernanda suarez, super car, girl with dark complexion, inspired by Ottilie Maclaren Wallace, deployed wings, motorsports photography, thick bushy straight eyebrows, full body cute young lady, fit curvy physique, matriarchy, ad, 1 0 / 1 0, asian decent', cost=None)
 
 ```
