### ISSUE TITLE
Unexpected error when calling promptEnhance() without the promptMaxLength param:  "AttributeError: 'IPromptEnhance' object has no attribute 'promptMaxLength'"

### ISSUE THREAD

**Issue by adilentiq** [Runware/sdk-python#17]
### Description
Unexpected error when calling promptEnhance() without the `promptMaxLength` param:  "AttributeError: 'IPromptEnhance' object has no attribute 'promptMaxLength'"

### Context
Runware Python SDK version: `runware==0.2.7`

### Requirements
 - Python installed on your workstation

### Reproduction steps

1. Create a directory

2. Create a file e.g `prompt_enhance.py` with the following content:
```python
from runware import Runware, IPromptEnhance
import asyncio
import os
from dotenv import load_dotenv

load_dotenv()


async def main() -> None:
    runware = Runware(
        api_key=os.getenv("RUNWARE_API_KEY"), url=os.getenv("RUNWARE_URL")
    )

    await runware.connect()

    payload = IPromptEnhance(promptMaxLength=60, promptVersions=1, prompt='cute cat')
    del payload.promptMaxLength

    res = await runware.promptEnhance(payload)

    print(f"Response : {res}")


asyncio.run(main())
```

3. Create a virtual environment
  ```bash
  python -m venv venv
  ```

4. Activate venv environment
  ```bash
  # Windows
  venv\Scripts\activate

  # Linux/MacOS
   source venv/bin/activate
  ```

5. Create a requirements.txt file with the following content:
```
aiofiles==23.2.1
asyncio==3.4.3
python-dotenv==1.0.1
runware==0.2.7
websockets==12.0
```

6. Install project dependencies:

```bash
 pip install -r requirements.txt
 ```
 
 7. Create `.env` file and set up environment variables
   ```bash
   touch .env
   source .env
  ```
   
   Example
   ```
   RUNWARE_API_KEY="your_runware_api_key"
  RUNWARE_URL="wss://ws-api.runware.ai/v1"
  RUNWARE_MODEL="runware:100@1"
  ```
  
  8. Run the python script
  ```bash
  python prompt_enhance.py
  ```

### Actual result

```bash
$ python prompt_enhance.py 
Traceback (most recent call last):
  File "C:\Users\andre\playground\prompt_enhance.py", line 24, in <module>
    asyncio.run(main())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\prompt_enhance.py", line 19, in main
    res = await runware.promptEnhance(payload)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 595, in promptEnhance
    raise e
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 593, in promptEnhance
    return await asyncRetry(lambda: self._enhancePrompt(promptEnhancer))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 43, in asyncRetry
    return await apiCall()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 607, in _enhancePrompt
    promptMaxLength = promptEnhancer.promptMaxLength or 380
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IPromptEnhance' object has no attribute 'promptMaxLength'
(venv)
```

### Expected result
Seems that the SDK tries to set up a default value(380) if the promptMaxLength  is not defined by the user,  so perhaps it can be fixed to make the call with 380.

**Comment by adilentiq** [comment]
A similar error is received when calling promptEnhance() with missing `promptVersions` parameter:

```bash
tests\prompt_enhance_test.py:56:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  
utils\client.py:171: in run
    response = asyncio.run(self.client.promptEnhance(payload))
..\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py:194: in run
    return runner.run(main)
..\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py:118: in run
    return self._loop.run_until_complete(task)
..\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:687: in run_until_complete
    return future.result()
venv\Lib\site-packages\runware\base.py:595: in promptEnhance
    raise e
venv\Lib\site-packages\runware\base.py:593: in promptEnhance
    return await asyncRetry(lambda: self._enhancePrompt(promptEnhancer))
venv\Lib\site-packages\runware\async_retry.py:50: in asyncRetry
    raise error
venv\Lib\site-packages\runware\async_retry.py:43: in asyncRetry
    return await apiCall()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  

self = <runware.server.RunwareServer object at 0x0000022258E8AF90>
promptEnhancer = <[AttributeError("'IPromptEnhance' object has no attribute 'promptVersions'") raised in repr()] IPromptEnhance object at 0x22258e8ad80>

    async def _enhancePrompt(
        self, promptEnhancer: IPromptEnhance
    ) -> List[IEnhancedPrompt]:
        """
        Internal method to perform the actual prompt enhancement.

        :param promptEnhancer: An IPromptEnhancer object containing the prompt details.
        :return: A list of IEnhancedPrompt objects representing the enhanced versions of the prompt.
        """
        prompt = promptEnhancer.prompt
        promptMaxLength = promptEnhancer.promptMaxLength or 380
>       promptVersions = promptEnhancer.promptVersions or 1
E       AttributeError: 'IPromptEnhance' object has no attribute 'promptVersions'

venv\Lib\site-packages\runware\base.py:608: AttributeError
===
```

**Comment by gorantosicpf** [comment]
@adilentiq I fixed it so that this parameter is not mandatory; the default will be 380.

**Comment by adilentiq** [comment]
Works fine:

```
Payload:

{'promptVersions': 2, 'prompt': 'A beautiful sunset over the mountains', 'includeCost': True}

Response:

[IEnhancedPrompt(taskType=<ETaskType.PROMPT_ENHANCE: 'promptEnhance'>, taskUUID='52a0d09a-8828-4e69-81fb-ebb5497ce319', text='A beautiful sunset over the mountains, iredescent soft glow bloom effect, dream - like, baroque painting, beautiful detailed intricate insanely detailed octane render trending on artstation, 8 k artistic photography, photorealistic, dramatic volumetric cinematic perfect light, chiaroscuro, award - winning photograph, masterpiece, raphael, caravaggio, greg rutkowski, beeple, beksinski', cost=0.0006), IEnhancedPrompt(taskType=<ETaskType.PROMPT_ENHANCE: 'promptEnhance'>, taskUUID='52a0d09a-8828-4e69-81fb-ebb5497ce319', text='A beautiful sunset over the mountains, Sandstone, Stone cave, huge waterfall in the distance, small cottage in the foreground, nighttime, moon in the night sky, cinematic, highly detailed painting by Stanley Artgerm Lau, greg rutkowski, thomas kindkade, alphonse mucha, loish, norman Rockwell', cost=0.0006)]
.
```
