### ISSUE TITLE
Add support to Python SDK to return the entire backend error object.

### ISSUE THREAD

**Issue by adilentiq** [Runware/sdk-python#26]
### Description
Seems that the Python SDK returns only the error message received from the backend, while doing the same operation directly via Websocket an error object is returned.

Example:

Error received via SDK:

```
runware.utils.RunwareError: Runware Error (Task UUID: 5afedf66-c056-4860-8ae2-f093ef602901): Invalid value for positivePrompt parameter. Positive prompt must be a string value.
```

Error received when using the Websocket:

```
[2024-09-12T19:19:39.512Z] Receiving response:

{
  errors: [
    {
      code: 'invalidPositivePrompt',
      message: 'Invalid value for positivePrompt parameter. Positive prompt must be a string value.',
      parameter: 'positivePrompt',
      type: 'string',
      documentation: 'https://docs.runware.ai/en/image-inference#positiveprompt',
      taskUUID: '6bb2cc2c-32ed-46fc-875c-ed8935da82b4'
    }
  ]
}
```

### Context
Runware Python SDK version: `runware==0.2.7`

### Requirements
 - Python installed on your workstation

### Reproduction steps

1. Create a directory

2. Create a file e.g `my_test.py` with the following content:
```python
from runware import Runware, IImageInference, IControlNetCanny
import asyncio
import os
from dotenv import load_dotenv

load_dotenv()


async def main() -> None:
    runware = Runware(
        api_key=os.getenv("RUNWARE_API_KEY"), url=os.getenv("RUNWARE_WSS_URL")
    )

    await runware.connect()

    request_image = IImageInference(
        positivePrompt="",
        negativePrompt="cloudy, rainy",
        model=os.getenv("RUNWARE_MODEL"),
        lora= [],
        numberResults=1,
        height=512,
        width=512,
        outputType=["URL"],
    )


    print(f"Payload: {request_image}")

    images = await runware.imageInference(requestImage=request_image)

    print(f"Images: {images}")


asyncio.run(main())

```

3. Create a virtual environment
  ```bash
  python -m venv venv
  ```

4. Activate venv environment
  ```bash
  # Windows
  venv\Scripts\activate

  # Linux/MacOS
   source venv/bin/activate
  ```

5. Create a requirements.txt file with the following content:
```
aiofiles==23.2.1
asyncio==3.4.3
python-dotenv==1.0.1
runware==0.2.7
websockets==12.0
```

6. Install project dependencies:

```bash
 pip install -r requirements.txt
 ```
 
 7. Create `.env` file and set up environment variables
   ```bash
   touch .env
   source .env
  ```
   
   Example
   ```
   RUNWARE_API_KEY="your_runware_api_key"
  RUNWARE_WSS_URL="wss://ws-api.runware.ai/v1"
  RUNWARE_MODEL="runware:100@1"
  ```
  
  8. Run the python script
  ```bash
  python my_test.py
  ```

### Actual result

```bash
$ python ./text_to_image.py 
Payload: IImageInference(positivePrompt='', model='civitai:81458@132760', taskUUID=None, outputType=['URL'], outputFormat=None, uploadEndpoint=None, checkNsfw=None, negativePrompt='cloudy, rainy', seedImage=None, maskImage=None, strength=None, height=512, width=512, steps=None, scheduler=None, seed=None, CFGScale=None, clipSkip=None, usePromptWeighting=None, numberResults=1, controlNet=[], lora=[], includeCost=None, useCache=None, onPartialImages=None)
Traceback (most recent call last):
  File "C:\Users\andre\playground\text_to_image.py", line 35, in <module>
    asyncio.run(main())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\text_to_image.py", line 30, in main
    images = await runware.imageInference(requestImage=request_image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 283, in imageInference
    raise e
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 267, in imageInference
    return await asyncRetry(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 43, in asyncRetry
    return await apiCall()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 322, in _requestImages
    images = await self.getSimililarImage(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 985, in getSimililarImage
    return await getIntervalWithPromise(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\utils.py", line 704, in getIntervalWithPromise       
    await future
runware.utils.RunwareError: Runware Error (Task UUID: 5afedf66-c056-4860-8ae2-f093ef602901): Invalid value for positivePrompt parameter. Positive prompt must be a string value.
(venv)

```

### Expected result
When using the Python SDK, I expect to receive the entire error object.

**Comment by gorantosicpf** [comment]
@adilentiq I added the new format of errors, please check it and let me know if I have to change someting
