### ISSUE TITLE
Add support for imageInference() to support local images for seedImage param.

### ISSUE THREAD

**Issue by adilentiq** [Runware/sdk-python#27]
### Description
I'm trying to run imageInference() with the seedImage parameter pointing to a local image, but I experience the error described below:

`runware.utils.RunwareError: Runware Error (Task UUID: 61d60e5b-5930-4ca4-9685-3c3c6da11368): Invalid value for seedImage parameter. The seed image must be specified in one of the following formats: a UUID v4 string of a previously uploaded or generated image, a data URI string, a base64 encoded image, or a publicly accessible URL. Supported formats are: PNG, JPG, and WEBP.`

It would be useful to be able to call imageInference() with seedImage: path to a local file.

### Context
Runware Python SDK version: `runware==0.2.7`

### Requirements
 - Python installed on your workstation

### Reproduction steps

1. Create a directory

2. In the directory add a test image e.g `image.jpg`
![image](https://github.com/user-attachments/assets/edceab48-a80c-466e-acd9-8ea0dfdeef7c)

3. Create a file e.g `image_to_image.py` with the following content:
```python
from runware import Runware, IImageInference
import asyncio
import os
from dotenv import load_dotenv

load_dotenv()


async def main() -> None:
    runware = Runware(
        api_key=os.getenv("RUNWARE_API_KEY"), url=os.getenv("RUNWARE_WSS_URL")
    )

    await runware.connect()

    payload = IImageInference(
            seedImage='image.jpg',
            positivePrompt="a beautiful sunset over the mountains",
            model=os.getenv("RUNWARE_MODEL"),
            numberResults=1,
            negativePrompt="cloudy, rainy",
            useCache=False,
            height=512,
            width=512,
            outputType="URL",
            outputFormat="PNG",
            includeCost=True,
            checkNsfw=True,
            CFGScale=10,
        )
        

    print(f"Payload: {payload}")

    result_image = await runware.imageInference(payload)

    print(f"Response : {result_image}")


asyncio.run(main())

```

4. Create a virtual environment
  ```bash
  python -m venv venv
  ```

5. Activate venv environment
  ```bash
  # Windows
  venv\Scripts\activate

  # Linux/MacOS
   source venv/bin/activate
  ```

6. Create a requirements.txt file with the following content:
```
aiofiles==23.2.1
asyncio==3.4.3
python-dotenv==1.0.1
runware==0.2.7
websockets==12.0
```

7. Install project dependencies:

```bash
 pip install -r requirements.txt
 ```
 
 8. Create `.env` file and set up environment variables
   ```bash
   touch .env
   source .env
  ```
   
   Example
   ```
   RUNWARE_API_KEY="your_runware_api_key"
  RUNWARE_WSS_URL="wss://ws-api.runware.ai/v1"
  RUNWARE_MODEL="runware:100@1"
  ```
  
  9. Run the python script
  ```bash
  python my_test.py
  ```

### Actual result

```bash
$ python ./image_to_image.py
Payload: IImageInference(positivePrompt='a beautiful sunset over the mountains', model='civitai:81458@132760', taskUUID=None, outputType='URL', outputFormat='PNG', uploadEndpoint=None, checkNsfw=True, negativePrompt='cloudy, rainy', seedImage='image.jpg', maskImage=None, strength=None, height=512, width=512, steps=None, scheduler=None, seed=None, CFGScale=10, clipSkip=None, usePromptWeighting=None, numberResults=1, controlNet=[], lora=[], includeCost=True, useCache=False, onPartialImages=None)
Traceback (most recent call last):
  File "C:\Users\andre\playground\image_to_image.py", line 40, in <module>
    asyncio.run(main())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\image_to_image.py", line 35, in main
    result_image = await runware.imageInference(payload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 283, in imageInference
    raise e
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 267, in imageInference
    return await asyncRetry(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 43, in asyncRetry
    return await apiCall()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 322, in _requestImages
    images = await self.getSimililarImage(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 985, in getSimililarImage
    return await getIntervalWithPromise(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\utils.py", line 704, in getIntervalWithPromise
    await future
runware.utils.RunwareError: Runware Error (Task UUID: 61d60e5b-5930-4ca4-9685-3c3c6da11368): Invalid value for seedImage parameter. The seed image must be specified in one of the following formats: a UUID v4 string of a previously uploaded or generated image, a data URI string, a base64 encoded image, or a publicly accessible URL. Supported formats are: PNG, JPG, and WEBP.
(venv)

```

### Expected result

seedImage should allow also the path to a local image.

**Comment by pasaranax** [comment]
use base64 encoded image like this
`seedImage=base64.b64encode(open('image.jpg', "b").read()).decode("utf-8")`

**Comment by gorantosicpf** [comment]
@adilentiq fixed

**Comment by adilentiq** [comment]
Hmm, still getting an error:

```
tests\image_to_image_test.py
 [2024-10-22 20:20:21.520771] Sending imageToImage() request to wss://ws-api.runware.dev/v1

{'positivePrompt': 'a beautiful sunset over the mountains', 'model': 'civitai:81458@132760', 'taskUUID': None, 'outputType': 'URL', 'outputFormat': 'PNG', 'uploadEndpoint': None, 'checkNsfw': True, 'negativePrompt': 'cloudy, rainy', 'seedImage': 'test_data\\sample.jpg', 'maskImage': None, 'strength': None, 'height': 512, 'width': 512, 'steps': None, 'scheduler': None, 'seed': None, 'CFGScale': 10, 'clipSkip': None, 'usePromptWeighting': None, 'numberResults': 1, 'controlNet': [], 'lora': [], 'includeCost': True, 'onPartialImages': None}
F

========================================================== FAILURES =========================================================== 
______________________________________ test_image_to_image_with_seed_image_a_local_file _______________________________________ 

runware_fixture = <runware.server.RunwareServer object at 0x0000022F79C41250>

    @pytest.mark.dev
    @pytest.mark.smoke
    @pytest.mark.image_to_image
    def test_image_to_image_with_seed_image_a_local_file(runware_fixture):
        # Init
        imageToImage = ImageToImage(runware_fixture)

        # Prepare payload
        payload = imageToImage.payload()

        payload.seedImage = os.path.join("test_data", "sample.jpg")

        # Make request
>       imageToImage.run(payload)

tests\image_to_image_test.py:113:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
utils\client.py:90: in run
    response = asyncio.run(self.client.imageInference(payload))
..\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py:194: in run
    return runner.run(main)
..\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py:118: in run
    return self._loop.run_until_complete(task)
..\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py:687: in run_until_complete
    return future.result()
venv\Lib\site-packages\runware\base.py:284: in imageInference
    raise e
venv\Lib\site-packages\runware\base.py:268: in imageInference
    return await asyncRetry(
venv\Lib\site-packages\runware\async_retry.py:50: in asyncRetry
    raise error
venv\Lib\site-packages\runware\async_retry.py:43: in asyncRetry
    return await apiCall()
venv\Lib\site-packages\runware\base.py:323: in _requestImages
    images = await self.getSimililarImage(
venv\Lib\site-packages\runware\base.py:994: in getSimililarImage
    return await getIntervalWithPromise(
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

callback = <function RunwareBase.getSimililarImage.<locals>.check at 0x0000022F79E77380>, debugKey = 'getting images'
timeOutDuration = 120000, shouldThrowError = False, pollingInterval = 100

    async def getIntervalWithPromise(
        callback: GetWithPromiseCallBackType,
        debugKey: str = "debugKey",
        timeOutDuration: int = TIMEOUT_DURATION,  # in milliseconds
        shouldThrowError: bool = True,
        pollingInterval: int = 100,  # in milliseconds
    ) -> Any:
        """
        Set up an interval to repeatedly call a callback function until a condition is met or a timeout occurs.

        :param callback: A function that is called repeatedly within the interval. It receives an object with
                         `resolve`, `reject`, and `intervalId` properties, allowing the callback to control
                         the promise's resolution or rejection and clear the interval if needed.
                         The callback should return a boolean value indicating whether to clear the interval.
        :param debugKey: A string used for debugging purposes. Default is "debugKey".
        :param timeOutDuration: The duration in milliseconds after which the promise will be rejected if the
                                callback hasn't resolved or rejected it. Default is TIMEOUT_DURATION.
        :param shouldThrowError: A boolean indicating whether to reject the promise with an error message if
                                 the timeout is reached. Default is True.
        :param pollingInterval: The interval in milliseconds at which the callback is invoked. Default is 100.
        :return: The result of the callback function or the rejection reason if the timeout is reached.

        Example:
            async def upload_image(task_uuid):
                image = await getIntervalWithPromise(
                    lambda params: params["resolve"]("uploadedImage") if "uploadedImage" in globals() else None,
                    debugKey="upload-image",
                    pollingInterval=200,
                )
                return image

            uploaded_image = await upload_image("task123")
            print(uploaded_image)  # Output: "uploadedImage"
        """
        logger = logging.getLogger(__name__)

        loop = asyncio.get_running_loop()
        future = loop.create_future()
        intervalHandle = None

        async def check_callback():
            nonlocal intervalHandle, future
            try:
                if not future.done():
                    # logger.debug(f"Checking callback for {debugKey}")
                    # logger.debug(f"Future done: {future.done()}")
                    # logger.debug(f"Future callback: {callback}")
                    # logger.debug(f"Future result: {future.result}")

                    # logger.debug(f"Future exception: {future.exception}")
                    # logger.debug(f"callback: {callback}")

                    result = callback(
                        future.set_result, future.set_exception, intervalHandle
                    )

                    if result:
                        if intervalHandle:
                            intervalHandle.cancel()
                            logger.debug(f"Interval cleared for {debugKey}")
                    else:
                        # TODO: Find a better way than polling, as it's not very efficient.
                        # Consider using asyncio.Event or asyncio.Condition triggered by an incoming message
                        # as the state won't change unless I have a new message from the service
                        intervalHandle = loop.call_later(
                            pollingInterval / 1000,
                            lambda: (
                                # logger.debug("Creating task for check_callback"),
                                asyncio.create_task(check_callback()),
                            )[-1],
                        )
                else:
                    logger.debug(
                        f"Future already done for {debugKey}, interval not rescheduled"
                    )
            except Exception as e:
                future.set_exception(e)
                logger.exception(f"Error in check_callback 2 for {debugKey}: {str(e)}")

        await check_callback()
        # intervalHandle = loop.call_later(
        #    pollingInterval / 1000,
        #    lambda: (
        #        logger.debug("Creating task for check_callback"),
        #        asyncio.create_task(check_callback()),
        #    )[
        #        -1
        #    ],  # Return the task itself)
        # )

        async def timeout_handler():
            nonlocal future, intervalHandle
            try:
                if not future.done():
                    if shouldThrowError:
                        future.set_exception(
                            Exception(f"Message could not be received for {debugKey}")
                        )
                        logger.error(f"Error: Message could not be received for {debugKey}")
                    else:
                        future.set_result(None)
                    if intervalHandle:
                        intervalHandle.cancel()
                        logger.debug(f"Interval cleared due to timeout for {debugKey}")
            except Exception as e:
                future.set_exception(e)
                logger.exception(f"Error in timeout_handler for {debugKey}: {str(e)}")

        # Schedule the timeout handler
        timeoutHandle = loop.call_later(
            timeOutDuration / 1000,
            lambda: (
                logger.debug("Creating task for timeout_handler"),
                asyncio.create_task(timeout_handler()),
            )[-1],
        )

        try:
>           await future
E           runware.utils.RunwareError: Runware Error (Task UUID: 00ff6d79-5034-4de3-b0d8-ad4c3e860854): Invalid value for seedImage parameter. The seed image must be specified in one of the following formats: a UUID v4 string of a previously uploaded or generated image, a data URI string, a base64 encoded image, or a publicly accessible URL. Supported formats are: PNG, JPG, and WEBP.

venv\Lib\site-packages\runware\utils.py:711: RunwareError
```
