### ISSUE TITLE
imageInference() with IControlNetCanny errors out: AttributeError: 'IControlNetCanny' object has no attribute 'include_hands_and_face_open_pose'

### ISSUE THREAD

**Issue by adilentiq** [Runware/sdk-python#28]
### Description
I'm encountering the following error when using imageInference() with IControlNetCanny:

`AttributeError: 'IControlNetCanny' object has no attribute 'include_hands_and_face_open_pose'`

### Context
Runware Python SDK version: `runware==0.2.7`

### Requirements
 - Python installed on your workstation

### Reproduction steps

1. Create a directory

2. Create a file e.g `my_test.py` with the following content:
```python
from runware import Runware, IImageInference, IControlNetCanny
import asyncio
import os
from dotenv import load_dotenv

load_dotenv()


async def main() -> None:
    runware = Runware(
        api_key=os.getenv("RUNWARE_API_KEY"), url=os.getenv("RUNWARE_WSS_URL")
    )

    await runware.connect()

    controlnet = IControlNetCanny(
        low_threshold_canny=100,
        high_threshold_canny=200,
        start_step=0,
        end_step=20,
        weight=1,
        control_mode="balanced",
        guide_image_unprocessed="https://huggingface.co/datasets/mishig/sample_images/resolve/main/canny-edge.jpg",
    )


    request_image = IImageInference(
        positivePrompt="a beautiful sunset over the mountains",
        negativePrompt="cloudy, rainy",
        model=os.getenv("RUNWARE_MODEL"),
        controlNet= [controlnet],
        numberResults=1,
        useCache=True,
        height=512,
        width=512,
        outputType=["URL"],
    )

    print(f"Payload: {request_image}")

    images = await runware.imageInference(requestImage=request_image)

    for image in images:
        print(f"Image URL: {image}")


asyncio.run(main())

```

3. Create a virtual environment
  ```bash
  python -m venv venv
  ```

4. Activate venv environment
  ```bash
  # Windows
  venv\Scripts\activate

  # Linux/MacOS
   source venv/bin/activate
  ```

5. Create a requirements.txt file with the following content:
```
aiofiles==23.2.1
asyncio==3.4.3
python-dotenv==1.0.1
runware==0.2.7
websockets==12.0
```

6. Install project dependencies:

```bash
 pip install -r requirements.txt
 ```
 
 7. Create `.env` file and set up environment variables
   ```bash
   touch .env
   source .env
  ```
   
   Example
   ```
   RUNWARE_API_KEY="your_runware_api_key"
  RUNWARE_WSS_URL="wss://ws-api.runware.ai/v1"
  RUNWARE_MODEL="runware:100@1"
  ```
  
  8. Run the python script
  ```bash
  python my_test.py
  ```

### Actual result

```bash
$ python text_to_image_controlnet.py 
Payload: IImageInference(positivePrompt='a beautiful sunset over the mountains', model='civitai:81458@132760', taskUUID=None, outputType=['URL'], outputFormat=None, uploadEndpoint=None, checkNsfw=None, negativePrompt='cloudy, rainy', seedImage=None, maskImage=None, strength=None, height=512, width=512, steps=None, scheduler=None, seed=None, CFGScale=None, clipSkip=None, usePromptWeighting=None, numberResults=1, controlNet=[IControlNetCanny(weight=1, start_step=0, end_step=20, control_mode='balanced', low_threshold_canny=100, high_threshold_canny=200, preprocessor=<EPreProcessor.canny: 'canny'>, guide_image=None, guide_image_unprocessed='https://huggingface.co/datasets/mishig/sample_images/resolve/main/canny-edge.jpg')], lora=[], includeCost=None, useCache=True, onPartialImages=None)
Traceback (most recent call last):
  File "C:\Users\andre\playground\text_to_image_controlnet.py", line 47, in <module>
    asyncio.run(main())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\text_to_image_controlnet.py", line 41, in main
    images = await runware.imageInference(requestImage=request_image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 283, in imageInference
    raise e
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 198, in imageInference
    includeHandsAndFaceOpenPose=any_control_data.include_hands_and_face_open_pose,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'IControlNetCanny' object has no attribute 'include_hands_and_face_open_pose'

```

**Comment by gorantosicpf** [comment]
@adilentiq I resolved this by adding the expected parameter needed to execute the image upload in the imageInference method. In that method, the parameter is a boolean with a default value of True, so I added the same to this class as well.

**Comment by adilentiq** [comment]
Getting a new error now:

```
$ python text_to_image.py 
Payload: IImageInference(positivePrompt='a beautiful sunset over the mountains', model='civitai:81458@132760', taskUUID=None, outputType=['URL'], outputFormat=None, uploadEndpoint=None, checkNsfw=None, negativePrompt='cloudy, rainy', seedImage=None, maskImage=None, strength=None, height=512, width=512, steps=None, scheduler=None, seed=None, CFGScale=None, clipSkip=None, usePromptWeighting=None, numberResults=1, controlNet=[IControlNetCanny(weight=1, start_step=0, end_step=20, control_mode='balanced', low_threshold_canny=100, high_threshold_canny=200, preprocessor=<EPreProcessor.canny: 'canny'>, guide_image=None, guide_image_unprocessed='https://huggingface.co/datasets/mishig/sample_images/resolve/main/canny-edge.jpg', include_hands_and_face_open_pose=True)], lora=[], includeCost=None, useCache=True, onPartialImages=None)
Traceback (most recent call last):
  File "C:\Users\andre\playground\text_to_image.py", line 47, in <module>
    asyncio.run(main())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete     
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\text_to_image.py", line 41, in main
    images = await runware.imageInference(requestImage=request_image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv\Lib\site-packages\runware\base.py", line 283, in imageInference
    raise e
  File "C:\Users\andre\playground\myvenv\Lib\site-packages\runware\base.py", line 209, in imageInference
    IControlNetWithUUID(
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\typing.py", line 1184, in __call__
    result = self.__origin__(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\typing.py", line 501, in __call__
    raise TypeError(f"Cannot instantiate {self!r}")
TypeError: Cannot instantiate typing.Union
```
