### ISSUE TITLE
Fix imageInference() to allow local images for maskImage parameter.

### ISSUE THREAD

**Issue by adilentiq** [Runware/sdk-python#32]
### Description
I'm trying to run imageInference() with the maskImage parameter pointing to a local image, but I experience the error described below:

`runware.utils.RunwareError: Runware Error (Task UUID: 1a3119f3-e364-4642-b0dc-df07ae32d82a): Invalid value for maskImage parameter. The mask image must be specified in one of the following formats: a UUID v4 string of a previously uploaded or generated image, a data URI string, a base64 encoded image, or a publicly accessible URL. Supported formats are: PNG, JPG, and WEBP.`

### Context
Runware Python SDK version: `runware==0.2.7`

### Requirements
 - Python installed on your workstation

### Reproduction steps

1. Create a directory

2. In the directory add a test image: `inpainting_mask_image.png`
![inpainting_mask_image](https://github.com/user-attachments/assets/039362fa-b013-4bb6-8bea-c550cbf54d17)

3. Create a file e.g `text_to_image.py` with the following content:
```python
from runware import Runware, IImageInference
import asyncio
import os
from dotenv import load_dotenv

load_dotenv()


async def main() -> None:
    runware = Runware(
        api_key=os.getenv("RUNWARE_API_KEY"), url=os.getenv("RUNWARE_WSS_URL")
    )

    await runware.connect()

    request_image = IImageInference(
        positivePrompt="cute dog",
        negativePrompt="cloudy, rainy",
        model=os.getenv("RUNWARE_MODEL"),
        lora= [],
        numberResults=1,
        height=512,
        width=512,
        seedImage="https://raw.githubusercontent.com/adilentiq/test-images/main/inpainting_source.png",
        maskImage="inpainting_mask_image.png"
    )


    print(f"Payload: {request_image}")

    images = await runware.imageInference(requestImage=request_image)

    print(f"Images: {images}")


asyncio.run(main())


```

4. Create a virtual environment
  ```bash
  python -m venv venv
  ```

5. Activate venv environment
  ```bash
  # Windows
  venv\Scripts\activate

  # Linux/MacOS
   source venv/bin/activate
  ```

6. Create a requirements.txt file with the following content:
```
aiofiles==23.2.1
asyncio==3.4.3
python-dotenv==1.0.1
runware==0.2.7
websockets==12.0
```

7. Install project dependencies:

```bash
 pip install -r requirements.txt
 ```
 
 8. Create `.env` file and set up environment variables
   ```bash
   touch .env
  ```
   
   Example
   ```
   RUNWARE_API_KEY="your_runware_api_key"
  RUNWARE_WSS_URL="wss://ws-api.runware.ai/v1"
  RUNWARE_MODEL="civitai:25694@31799" # any Inpainting model
  ```
  
  9. Run the python script
  ```bash
  python my_test.py
  ```

### Actual result

```bash
$ python ./text_to_image.py 
Payload: IImageInference(positivePrompt='cute dog', model='civitai:81458@132760', taskUUID=None, outputType=None, outputFormat=None, uploadEndpoint=None, checkNsfw=None, negativePrompt='cloudy, rainy', seedImage='https://raw.githubusercontent.com/adilentiq/test-images/main/inpainting_source.png', maskImage='inpainting_mask_image.png', strength=None, height=512, width=512, steps=None, scheduler=None, seed=None, CFGScale=None, clipSkip=None, usePromptWeighting=None, numberResults=1, controlNet=[], lora=[], includeCost=None, useCache=None, onPartialImages=None)
Traceback (most recent call last):
  File "C:\Users\andre\playground\text_to_image.py", line 36, in <module>
    asyncio.run(main())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\text_to_image.py", line 31, in main
    images = await runware.imageInference(requestImage=request_image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 283, in imageInference
    raise e
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 267, in imageInference
    return await asyncRetry(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\async_retry.py", line 43, in asyncRetry
    return await apiCall()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 322, in _requestImages
    images = await self.getSimililarImage(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 985, in getSimililarImage
    return await getIntervalWithPromise(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\utils.py", line 704, in getIntervalWithPromise    
    await future
runware.utils.RunwareError: Runware Error (Task UUID: 1a3119f3-e364-4642-b0dc-df07ae32d82a): Invalid value for maskImage parameter. The mask image must be specified in one of the following formats: a UUID v4 string of a previously uploaded or generated image, a data URI string, a base64 encoded image, or a publicly accessible URL. Supported formats are: PNG, JPG, and WEBP.
```

### Expected result

maskImage should allow also the path to a local image.

**Comment by gorantosicpf** [comment]
@adilentiq

**Comment by adilentiq** [comment]
Still getting an error:

```
$ python ./text_to_image.py 
Payload: IImageInference(positivePrompt='cute dog', model='civitai:81458@132760', taskUUID=None, outputType=None, outputFormat=None, uploadEndpoint=None, checkNsfw=None, negativePrompt='cloudy, rainy', seedImage='https://raw.githubusercontent.com/adilentiq/test-images/main/inpainting_source.png', maskImage='inpainting_mask_image.png', strength=None, height=512, width=512, steps=None, scheduler=None, seed=None, CFGScale=None, clipSkip=None, usePromptWeighting=None, numberResults=1, controlNet=[], lora=[], includeCost=None, onPartialImages=None)
Traceback (most recent call last):
  File "C:\Users\andre\playground\text_to_image.py", line 36, in <module>
    asyncio.run(main())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\text_to_image.py", line 31, in main
    images = await runware.imageInference(requestImage=request_image)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv\Lib\site-packages\runware\base.py", line 284, in imageInference
    raise e
  File "C:\Users\andre\playground\myvenv\Lib\site-packages\runware\base.py", line 268, in imageInference
    return await asyncRetry(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\myvenv\Lib\site-packages\runware\async_retry.py", line 43, in asyncRetry
    images = await self.getSimililarImage(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv\Lib\site-packages\runware\base.py", line 994, in getSimililarImage
    return await getIntervalWithPromise(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv\Lib\site-packages\runware\utils.py", line 711, in getIntervalWithPromise
    await future
runware.utils.RunwareError: Runware Error (Task UUID: f9caa1ea-b247-44ea-b67c-f8b4ddf6d996): Invalid value for maskImage parameter. The mask image must be specified in one of the following formats: a UUID v4 string of a previously uploaded or generated image, a data URI string, a base64 encoded image, or a publicly accessible URL. Supported formats are: PNG, JPG, and WEBP.

```
