### ISSUE TITLE
Error when calling imageUpscale() with a valid URL for inputImage param: "sys:1: RuntimeWarning: coroutine 'RunwareBase._isLocalFile' was never awaited"

### ISSUE THREAD

**Issue by adilentiq** [Runware/sdk-python#52]
### Description
Seems that imageUpscale throws an error when using the runware SDK from `main` branch:

```
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\base.py", line 722, in _uploadImage
    image_base64 = await fileToBase64(file) if isinstance(file, str) else file
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\utils.py", line 306, in fileToBase64
    raise IOError(f"The file at {file_path} could not be read.")
OSError: The file at https://raw.githubusercontent.com/adilentiq/test-images/refs/heads/main/test.jpg could not be read.sys:1: RuntimeWarning: coroutine 'RunwareBase._isLocalFile' was never awaited
```

### Context
OS: Windows
Python version: `Python 3.12.5`
SDK version: main branch

### Requirements
 - Python installed on your workstation

### Reproduction steps

1. Create a directory

2. Create a file e.g `my_script.py` with the following content:
```python
from runware import Runware, IImageUpscale
import asyncio
import os
from dotenv import load_dotenv

load_dotenv(override=True)


async def main() -> None:
    runware = Runware(
        api_key=os.getenv("RUNWARE_API_KEY"), url=os.getenv("RUNWARE_WSS_URL")
    )

    await runware.connect()

    image_url = 'https://raw.githubusercontent.com/adilentiq/test-images/refs/heads/main/test.jpg'
    payload = IImageUpscale(inputImage=image_url, upscaleFactor=2)

    print(f"Payload: {payload}")

    result_image = await runware.imageUpscale(payload)

    print(f"Response : {result_image}")


asyncio.run(main())

```

3. Create a virtual environment
  ```bash
  python -m venv venv
  ```

4. Activate venv environment
  ```bash
  # Windows
  venv\Scripts\activate

  # Linux/MacOS
   source venv/bin/activate
  ```

5. Create a requirements.txt file with the following content:
```
aiofiles==23.2.1
asyncio==3.4.3
python-dotenv==1.0.1
websockets==12.0
git+https://github.com/Runware/sdk-python.git@main
```

6. Install project dependencies:

```bash
 pip install -r requirements.txt
 ```
 
 7. Create `.env` file and set up environment variables
   ```bash
   touch .env
  ```
   
   Example
   ```
   RUNWARE_API_KEY="your_api_key_here"
  RUNWARE_WSS_URL="wss://ws-api.runware.dev/v1"
  RUNWARE_MODEL="civitai:81458@132760"
  ```
  
  8. Run the python script
  ```bash
  python my_script.py
  ```

### Actual result

```bash
$ python image_upscale.py 
Payload: IImageUpscale(inputImage='https://raw.githubusercontent.com/adilentiq/test-images/refs/heads/main/test.jpg', upscaleFactor=2, outputType=None, outputFormat=None, includeCost=False)
Traceback (most recent call last):
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\utils.py", line 294, in fileToBase64
    async with aiofiles.open(file_path, "rb") as file:
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\aiofiles\base.py", line 98, in __aenter__
    self._obj = await self._coro
                ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\aiofiles\threadpool\__init__.py", line 94, in _open
    f = yield from loop.run_in_executor(executor, cb)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run       
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'https://raw.githubusercontent.com/adilentiq/test-images/refs/heads/main/test.jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andre\playground\image_upscale.py", line 26, in <module>
    asyncio.run(main())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\image_upscale.py", line 21, in main
    result_image = await runware.imageUpscale(payload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\base.py", line 521, in imageUpscale
    raise e
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\base.py", line 519, in imageUpscale
    return await asyncRetry(lambda: self._upscaleGan(upscaleGanPayload))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\async_retry.py", line 43, in asyncRetry
    return await apiCall()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\base.py", line 527, in _upscaleGan
    image_uploaded = await self.uploadImage(inputImage)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\base.py", line 671, in uploadImage
    raise e
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\base.py", line 669, in uploadImage
    return await asyncRetry(lambda: self._uploadImage(file))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\async_retry.py", line 50, in asyncRetry
    raise error
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\async_retry.py", line 43, in asyncRetry
    return await apiCall()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\base.py", line 722, in _uploadImage
    image_base64 = await fileToBase64(file) if isinstance(file, str) else file
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\myvenv2\Lib\site-packages\runware\utils.py", line 306, in fileToBase64
    raise IOError(f"The file at {file_path} could not be read.")
OSError: The file at https://raw.githubusercontent.com/adilentiq/test-images/refs/heads/main/test.jpg could not be read.sys:1: RuntimeWarning: coroutine 'RunwareBase._isLocalFile' was never awaited
```

**Comment by gorantosicpf** [comment]
@adilentiq Should be ok now

**Comment by adilentiq** [comment]
Re-tested, works fine now.
