### ISSUE TITLE
 FileNotFoundError error when calling imageInference() with seedImage a valid image uuid.

### ISSUE THREAD

**Issue by adilentiq** [Runware/sdk-python#61]
### Description
I'm getting the following error when calling imageInference() with seedImage parameter a valid image uuid:

`FileNotFoundError: The file at 698d7bea-fb92-47e7-9ec7-e98d51ecf409 does not exist.`

### Context
OS: Windows
Python version: `Python 3.12.5`
SDK version: main branch

### Requirements
 - Python installed on your workstation

### Reproduction steps

1. Create a directory

2. Create a file e.g `my_test.py` with the following content:

```


```
from runware import Runware, IImageInference, IImageBackgroundRemoval
import asyncio
import os
from dotenv import load_dotenv

load_dotenv()

async def main() -> None:
    runware = Runware(
        api_key=os.getenv("RUNWARE_API_KEY"), url=os.getenv("RUNWARE_WSS_URL"),
        #log_level='DEBUG'
        
    )

    await runware.connect()

    payload = IImageInference(
            positivePrompt="a beautiful sunset over the mountains",
            model=os.getenv("RUNWARE_MODEL"),
            numberResults=1,
            negativePrompt="cloudy, rainy",
            height=512,
            width=512,
            outputType=["URL", "base64Data"],
            outputFormat="PNG",
            includeCost=True,
            checkNsfw=True,
            CFGScale=10,
            seedImage='698d7bea-fb92-47e7-9ec7-e98d51ecf409'
        )
        

    print(f"\nimageInference Payload: {payload}")

    images = await runware.imageInference(payload)
    my_image = images[0]

    print(f"\nimageInference Response : {my_image}")

asyncio.run(main())

```

3. Create a virtual environment
  ```bash
  python -m venv venv
  ```

4. Activate venv environment
  ```bash
  # Windows
  venv\Scripts\activate

  # Linux/MacOS
   source venv/bin/activate
  ```

5. Create a requirements.txt file with the following content:
```
aiofiles==23.2.1
asyncio==3.4.3
python-dotenv==1.0.1
runware==0.2.7
websockets==12.0
git+https://github.com/Runware/sdk-python.git@main
```

6. Install project dependencies:

```bash
 pip install -r requirements.txt
 ```
 
 7. Create `.env` file and set up environment variables
   ```bash
   touch .env
  ```
   
   Example
   ```
   RUNWARE_API_KEY="your_runware_api_key"
  RUNWARE_WSS_URL="wss://ws-api.runware.ai/v1"
  RUNWARE_MODEL="civitai:81458@132760"
  ```
  
  8. Run the python script
  ```bash
  python my_test.py
  ```

### Actual result

```bash
$ python my_test.py 

imageInference Payload: IImageInference(positivePrompt='a beautiful sunset over the mountains', model='civitai:81458@132760', taskUUID=None, outputType=['URL', 'base64Data'], outputFormat='PNG', uploadEndpoint=None, checkNsfw=True, negativePrompt='cloudy, rainy', seedImage='698d7bea-fb92-47e7-9ec7-e98d51ecf409', maskImage=None, strength=None, height=512, width=512, steps=None, scheduler=None, seed=None, CFGScale=10, clipSkip=None, usePromptWeighting=None, numberResults=1, controlNet=[], lora=[], includeCost=True, onPartialImages=None)
Traceback (most recent call last):
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\utils.py", line 294, in fileToBase64
    async with aiofiles.open(file_path, "rb") as file:
  File "C:\Users\andre\playground\venv\Lib\site-packages\aiofiles\base.py", line 98, in __aenter__
    self._obj = await self._coro
                ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\aiofiles\threadpool\__init__.py", line 94, in _open
    f = yield from loop.run_in_executor(executor, cb)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '698d7bea-fb92-47e7-9ec7-e98d51ecf409'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\andre\playground\text_to_image.py", line 42, in <module>
    asyncio.run(main())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\text_to_image.py", line 36, in main
    images = await runware.imageInference(payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 294, in imageInference
    raise e
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\base.py", line 180, in imageInference
    requestImage.seedImage = await fileToBase64(requestImage.seedImage)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\andre\playground\venv\Lib\site-packages\runware\utils.py", line 304, in fileToBase64
    raise FileNotFoundError(f"The file at {file_path} does not exist.")
FileNotFoundError: The file at 698d7bea-fb92-47e7-9ec7-e98d51ecf409 does not exist.

```

**Comment by gorantosicpf** [comment]
@adilentiq The fix is here: https://github.com/Runware/sdk-python/pull/64
