### ISSUE TITLE
ImportError: cannot import name 'Runware' from partially initialized module 'runware'

### ISSUE THREAD

**Issue by stawiski** [Runware/sdk-python#89]
Trying the example from your docs: https://runware.ai/docs/en/libraries/python:
```
% python runware.py
Traceback (most recent call last):
  File "/Users/m/MobileApp/ipad-app/runware.py", line 1, in <module>
    from runware import Runware, IImageInference
  File "/Users/m/MobileApp/ipad-app/runware.py", line 1, in <module>
    from runware import Runware, IImageInference
```
on `Python 3.13.0`.

**Comment by stawiski** [comment]
nvm
